RapidApiProject/Models/ErrorViewModel.cs
namespace RapidApiProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RapidApiProject/Models/ExhangeViewModel.cs
namespace RapidApiProject.Models
{
    public class ExhangeViewModel
    {
        public string base_currency { get; set; }
        public Exchange_Rates[] exchange_rates { get; set; }
        public string base_currency_date { get; set; }
    }
    public class Exchange_Rates
    {
        public string currency { get; set; }
        public string exchange_rate_buy { get; set; }
    }
}

RapidApiProject/Models/SearchLocationViewModel.cs
namespace RapidApiProject.Models
{
    public class SearchLocationViewModel
    {
        public string dest_id { get; set; }
    }
}

RapidApiProject/Models/SeriesViewModel.cs
namespace RapidApiProject.Models
{
    public class SeriesViewModel
    {
        public int rank { get; set; }
        public string title { get; set; }
        public decimal rating { get; set; }
        public string image { get; set; }
        public string imdb_link { get; set; }
    }
}

RapidApiProject/Controllers/ExchangeController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RapidApiProject.Models;
using System.Net.Http.Headers;

namespace RapidApiProject.Controllers
{
    public class ExchangeController : Controller
    {
        public async Task<IActionResult> Index()
        {

            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://booking-com.p.rapidapi.com/v1/metadata/exchange-rates?currency=USD&locale=en-gb"),
                Headers =
    {
        { "X-RapidAPI-Key", "ed120ca162msh4a2cf1663625a24p1cae18jsn548260e0d857" },
        { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
    },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();
                var values = JsonConvert.DeserializeObject<ExhangeViewModel>(body);
                return View(values.exchange_rates.ToList());
            }
        }
    }
}

RapidApiProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RapidApiProject.Models;
using System.Diagnostics;

namespace RapidApiProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RapidApiProject/Controllers/MovieSeriesController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RapidApiProject.Models;
using System.Net.Http.Headers;

namespace RapidApiProject.Controllers
{
    public class MovieSeriesController : Controller
    {
        public async Task<IActionResult> Index()
        {
            var client = new HttpClient();
            var request = new HttpRequestMessage
            {
                Method = HttpMethod.Get,
                RequestUri = new Uri("https://imdb-top-100-movies.p.rapidapi.com/series/"),
                Headers =
    {
        { "X-RapidAPI-Key", "ed120ca162msh4a2cf1663625a24p1cae18jsn548260e0d857" },
        { "X-RapidAPI-Host", "imdb-top-100-movies.p.rapidapi.com" },
    },
            };
            using (var response = await client.SendAsync(request))
            {
                response.EnsureSuccessStatusCode();
                var body = await response.Content.ReadAsStringAsync();
                var values=JsonConvert.DeserializeObject<List<SeriesViewModel>>(body);
                return View(values);
            }
            
        }
    }
}

RapidApiProject/Controllers/SearchLocationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using RapidApiProject.Models;
using System.Net.Http.Headers;

namespace RapidApiProject.Controllers
{
    public class SearchLocationController : Controller
    {
        public async Task<IActionResult> Index(string city)
        {
            if (!string.IsNullOrEmpty(city))
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri($"https://booking-com.p.rapidapi.com/v1/hotels/locations?name={city}&locale=en-gb"),
                    Headers =
    {
        { "X-RapidAPI-Key", "ed120ca162msh4a2cf1663625a24p1cae18jsn548260e0d857" },
        { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
    },
                };
                using (var response = await client.SendAsync(request))
                {
                    response.EnsureSuccessStatusCode();
                    var body = await response.Content.ReadAsStringAsync();
                    var values = JsonConvert.DeserializeObject<List<SearchLocationViewModel>>(body);

                    return View(values.ToList());
                }
            }
            else
            {
                var client = new HttpClient();
                var request = new HttpRequestMessage
                {
                    Method = HttpMethod.Get,
                    RequestUri = new Uri("https://booking-com.p.rapidapi.com/v1/hotels/locations?name=istanbul&locale=en-gb"),
                    Headers =
    {
        { "X-RapidAPI-Key", "ed120ca162msh4a2cf1663625a24p1cae18jsn548260e0d857" },
        { "X-RapidAPI-Host", "booking-com.p.rapidapi.com" },
    },
                };
                using (var response = await client.SendAsync(request))
                {
                    response.EnsureSuccessStatusCode();
                    var body = await response.Content.ReadAsStringAsync();
                    var values = JsonConvert.DeserializeObject<List<SearchLocationViewModel>>(body);

                    return View(values.ToList());
                }

            }
          
        }
    }
}

RapidApiProject/Views/Exchange/Index.cshtml
@model List<Exchange_Rates>
@{
    Layout = null;
}

<div class="container">
    <table class="table table-bordered">
        <tr>
            <th>Döviz</th>
            <th>Kur</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.currency</td>
                <td>@item.exchange_rate_buy</td>
            </tr>
        }
    </table>

<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

RapidApiProject/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

RapidApiProject/Views/MovieSeries/Index.cshtml
@model List<SeriesViewModel>
@{
    Layout = null;
}
<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

<div class="container">
<h2>Imdb Top 100 Dizi</h2>
    <table class="table table-hover">
        <tr>
            <th>#</th>
            <th>Dizi Adı</th>
            <th>Dizi Puanı</th>
            <th>Detaylar</th>
        </tr>
        @foreach (var item in Model)
        {
            
        
        <tr>
            <td>@item.rank</td>
            <td>@item.title</td>
            <td>@item.rating</td>
                <td><a href="@item.imdb_link" class="btn btn-primary">Git</a></td>
        </tr>
        }
    </table>

</div>

RapidApiProject/Views/SearchLocation/Index.cshtml
@model List<SearchLocationViewModel>
@{
    Layout = null;
}

<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />

<div class="container">
    <br /><br />
    @using(Html.BeginForm("Index","SearchLocation",FormMethod.Post))
    {
        <label>Şehir adını giriniz.</label>
        <input type="text" class="form-control" name="city" />
       <br />
        <button class="btn btn-dark">Getir</button>
    }
    <hr />
    <table class="table table-hover">
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.dest_id</td>
            </tr>
        }
    </table>
</div>

RapidApiProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RapidApiProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RapidApiProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RapidApiProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - RapidApiProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>